/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NCafeManagement;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.awt.*;

/**
 *
 * @author Arya Prathama
 */


    /**
     * Creates new form AdminManagerGUI
     */
    public class RegularAdminGUI extends javax.swing.JFrame {
        String Username;
        String Password;
        String loggedInUsername;

        /**
         * Creates new form AdminManagerGUI
         */
        public RegularAdminGUI() {
            setTitle("Regular Admin");
            initComponents();
            this.setLocationRelativeTo(null);
        }

        public RegularAdminGUI(String username, String password) {
            setTitle("Regular Admin");
            initComponents();
            this.setLocationRelativeTo(null);

            initComponents();
            Username = username;
            Password = password;
            loggedInUsername = username;


        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ViewAdminbtn = new javax.swing.JButton();
        ChangePWbutton = new javax.swing.JButton();
        BackAdminbutton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtableRegularAdmin = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        ViewAdminbtn.setText("View Admin");
        ViewAdminbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewAdminbuttonMouseClicked(evt);
            }
        });

        ChangePWbutton.setText("Change Admin Password");
        ChangePWbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePWbuttonMouseClicked(evt);
            }
        });

        BackAdminbutton.setText("Back");
        BackAdminbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackAdminbuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(ViewAdminbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(ChangePWbutton)
                .addGap(78, 78, 78)
                .addComponent(BackAdminbutton)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewAdminbtn)
                    .addComponent(ChangePWbutton)
                    .addComponent(BackAdminbutton))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        JtableRegularAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Username", "Status"
            }
        ));
        jScrollPane2.setViewportView(JtableRegularAdmin);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        Connection Con = null;
        PreparedStatement pst = null;
        ResultSet Rs = null;
        Statement St = null;
        private void ViewAdminbuttonMouseClicked(java.awt.event.MouseEvent evt) {
            try {
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/warned_db", "root", "");
                Statement statement = connection.createStatement();

                ResultSet resultSet = statement.executeQuery("SELECT * FROM tb_username");

                DefaultTableModel model = (DefaultTableModel) JtableRegularAdmin.getModel();
                model.setRowCount(0);
                while (resultSet.next()) {
                    String username = resultSet.getString("Username");
                    String adminType = resultSet.getString("Status");
                    model.addRow(new Object[]{username, adminType});
                }

                resultSet.close();
                statement.close();
                connection.close();
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Failed to connect to database.");
            }
        }
        private void ChangePWbuttonMouseClicked(java.awt.event.MouseEvent evt) {

            try {
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/warned_db", "root", "");
                Statement statement = connection.createStatement();
                String usernameInput = JOptionPane.showInputDialog(this, "Enter your username ");
                ResultSet resultSet = statement.executeQuery("SELECT * FROM tb_username WHERE Username='" + usernameInput + "'");
                if (resultSet.next()) {
                    String passwordDatabase = resultSet.getString("Password");
                    String passwordInput = JOptionPane.showInputDialog(this, "Enter your old password ");
                    if (passwordInput.equals(passwordDatabase)) {
                        String confirmation = JOptionPane.showInputDialog(this, "Confirm your old password ");
                        if (confirmation.equals(passwordInput)) {
                            String newPassword = JOptionPane.showInputDialog(this, "Enter your new password ");
                            statement.executeUpdate("UPDATE tb_username SET Password='" + newPassword + "' WHERE Username='" + usernameInput + "'");
                            JOptionPane.showMessageDialog(this, "Password changed successfully!");
                        } else {
                            JOptionPane.showMessageDialog(this, "Password doesn't match!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Wrong password!");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Username not found!");
                }
                resultSet.close();
                statement.close();
                connection.close();
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Failed to connect to database.");
            }

        }

        private void BackAdminbuttonMouseClicked(java.awt.event.MouseEvent evt) {
                AfterLoginGui afterLoginGui = new AfterLoginGui(loggedInUsername, Password);
                afterLoginGui.setVisible(true);
                this.dispose();

        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(RegularAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(RegularAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(RegularAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(RegularAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new RegularAdminGUI().setVisible(true);
                }
            });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackAdminbutton;
    private javax.swing.JButton ChangePWbutton;
    private javax.swing.JTable JtableRegularAdmin;
    private javax.swing.JButton ViewAdminbtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    }

